# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    tags: '*'
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: build static files
      run: yarn && yarn install && yarn build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: build # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: dist/

#     - name: Release
#       uses: fnkr/github-action-ghr@v1
#       if: startsWith(github.ref, 'refs/tags/')
#       env:
#         GHR_COMPRESS: xz
#         GHR_PATH: dist/
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Add artifacts to release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        args:
        - dist/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
